- i18n/en.json
- web/src/components/LogsTable.js
这个页面载入和刷新都调用了总消耗额度求和，日志多了之后容易造成慢查询，尤其是用户端不停刷新的时候；
实际没有太多必要，改为默认隐藏，让用户主动点击去查询。
> feat: add toggleable visibility for total quota using an eye icon

- controller/log.go
- controller/relay-audio.go
- controller/relay-image.go
- controller/relay-text.go
- model/ability.go
- model/cache.go
- model/channel.go
- model/log.go
- web/src/components/ChannelsTable.js
- web/src/components/LogsTable.js
支持设置渠道优先级，如果有多个渠道，想尽快刷完某个渠道，可以通过设置优先级，来强制使用此渠道
结合自动关闭渠道，可以做到按顺序一个一个刷完
对于优先级为0的，还是按照一起的随机取一个。
日志显示渠道ID，并支持筛选，更方便计算渠道消耗。
> feat: 支持设置渠道优先级 & 日志中显示使用的渠道ID

- web/src/components/TokensTable.js
> 解决令牌页面聊天按钮丢失url参数的问题

- docker-compose.yml
> fix: docker compose healthcheck failed

- controller/relay-text.go
close #599
Use `float64` during calc and do `math.Ceil` after calc. 
This will result in the quota being used slightly more than the official standard, but it will be guaranteed that it will not be less.
> fix: change quota calc code (close #599)

- web/src/components/ChannelsTable.js
- web/src/components/RedemptionsTable.js
- web/src/components/TokensTable.js
- web/src/components/UsersTable.js
There was an issue with the sorting function in the user table where **numeric values were being treated as strings**, leading to incorrect order. 
Specifically, "10" was being sorted next to "1", rather than after "9".
This PR ensures that both numeric and string values are sorted correctly in the user table. See below:
> fix: Numeric Sorting in Tables

- common/gin.go
- controller/relay.go
- middleware/distributor.go
close #719
只是临时修复，将之前移除的`if`加了回来，让这两个接口能用。  
彻底解决需要`common.UnmarshalBodyReusable`能同时支持`application/json`和`multipart/form-data`。  
已经在我的环境里测试通过。
> fix: Skip JSON deserialization when accessing transcriptions and translations.

- common/email.go
我们在发送电子邮件到 Gmail 时遇到了邮件拒收的问题。Gmail 服务器返回的错误信息如下：
> host gmail-smtp-in.l.google.com[] said: 550-5.7.1 [] Messages missing a valid Message-ID header are not accepted. Please visit https://support.google.com/mail/?p=RfcMessageNonCompliant and review RFC 5322 specifications for more information. 
这表明我们的邮件因为缺少有效的 `Message-ID` 标头而被 Gmail 拒绝接收。根据 RFC 5322 规范，`Message-ID` 是电子邮件标准协议的一部分，每封邮件都需要一个唯一的 `Message-ID`。
为了解决这个问题，我在邮件发送功能中添加了生成和包含 `Message-ID` 的逻辑。`Message-ID` 是根据发件人的电子邮件地址动态生成的，确保了每封邮件都具有唯一的标识符。
修改后的代码主要在 `SendEmail` 函数中进行了以下更改：
1. 从 `SMTPFrom` 中提取域名部分。
2. 使用 `crypto/rand` 包生成一串随机字符。
3. 将这些字符和域名组合成一个唯一的 `Message-ID`。
4. 在邮件头信息中添加这个 `Message-ID`。
通过这些更改，我们的邮件现在包含了符合 RFC 5322 规范的有效 `Message-ID`，成功解决了 Gmail 拒收的问题。
---
请审阅这些更改，并考虑合并到主分支。如果有任何问题或需要进一步的讨论，请随时与我联系。
> feat: 发送邮件时添加 Message-ID 

- controller/relay-audio.go
使用时需要注意 API 版本，`2023-09-01-preview`。  
另外 Azure OpenAI 给的配额不够，一个人使用可能勉强还行；  
用量大的话建议走 OpenAI 官方或者 Azure 自己的 [Speech to text](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-speech-to-text?tabs=windows%2Cterminal&pivots=programming-language-rest) 和 [Text to speech](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-text-to-speech?tabs=windows%2Cterminal&pivots=programming-language-rest)。
已经在我的环境测试通过。
> feat: Support Azure OpenAI Whisper.

- controller/relay-audio.go
- controller/relay.go
The parsing logic for responses in relay.go and relay-audio.go was refactored to support multiple response formats - 'json', 'text', 'srt', 'verbose_json', and 'vtt'. The existing `WhisperResponse` struct was renamed to `WhisperJsonResponse` and a new struct `WhisperVerboseJsonResponse` was added to support the 'verbose_json' format. Additional parsing functions were added to extract text from these new response types. This change was necessary to make the parsing logic more flexible and extendable for different types of responses.
close #735 
whisper 模型 支持多种format响应（ 'json', 'text', 'srt', 'verbose_json', and 'vtt'）
> feat: Refactor response parsing logic to support multiple formats

- README.en.md
- README.ja.md
- README.md
- common/constants.go
- common/model-ratio.go
- controller/channel-test.go
- controller/model.go
- controller/relay-gemini-chat.go
- controller/relay-gemini.go
- controller/relay-text.go
- middleware/distributor.go
- web/src/constants/channel.constants.js
- web/src/pages/Channel/EditChannel.js
> feat: add Google Gemini Pro support

- controller/relay-image.go
close #811 
对于官方文档，当没有设置参数n时，会默认为1。有些应用的请求没有默认n=1，会导致报错
> feat: reset image num to 1 when not given

- README.md
- common/database.go
- model/main.go
在使用sqlite时，高并发下，用户余额更新操作时出现了失败的情况，报database is lock错误，从而导致用户余额更新不一致，添加busy_timeout参数，设置为3000毫秒，当数据库被锁定时，任何操作都会等待最多3秒钟的时间以获取数据库锁。
> feat: able to set sqlite busy_timeout

- controller/relay-image.go
- Add a condition to validate the n value only for non-Azure channels, ensuring it falls within the acceptable range.
- Fix Azure requestUrl compatibility
> fix: Azure 渠道调用DALLE模型报错n_not_within_range

- common/image/image.go
- common/image/image_test.go
gpt-4 vision 传入base64字符串时，没有将base64解码，导致图片解析失败。
将base64解码后，读取正常
> fix: gpt-4 vision 传入 base64 字符串图片时解析错误

- common/model-ratio.go
- controller/relay-ali.go
- web/src/pages/Channel/EditChannel.js
通义千问支持stream的增量模式，不需要每次去掉上次的前缀；实测qwen-max联网模式效果不错，添加了联网模式。如果别的模型有问题可以改为单独给qwen-max开放
> feat: 改进阿里模型 stream 模式 & 使其支持联网搜索能力

- controller/relay-ali.go
- controller/relay-baidu.go
- controller/relay-claude.go
- controller/relay-gemini.go
- controller/relay-palm.go
- controller/relay-tencent.go
- controller/relay-zhipu.go
- controller/relay.go
<https://github.com/zurawiki/gptcommit> 这样的工具可以使用 openai 为 git 生成 commit 信息，但是只支持 gpt。
我试图用 one-api 将 gpt 请求转发给 google gemini，但是 gptcommit 报错称 response 中找不到 model 字段。
根据[ OpenAI 官方文档](https://platform.openai.com/docs/api-reference/chat/create)，gpt chat completion 的返回结构应为：
```json
{
"id": "chatcmpl-123",
"object": "chat.completion",
"created": 1677652288,
"model": "gpt-3.5-turbo-0613",
"system_fingerprint": "fp_44709d6fcb",
"choices": [{
"index": 0,
"message": {
"role": "assistant",
"content": "\n\nHello there, how may I assist you today?",
},
"logprobs": null,
"finish_reason": "stop"
}],
"usage": {
"prompt_tokens": 9,
"completion_tokens": 12,
"total_tokens": 21
}
}
```
one-api relay 的 `OpenAITextResponse` 结构中确实缺少了 `Model` 字段。
所以本 PR 为这个结构体和 gemini、claude 都加上了 Model 的返回。
自测 OK，one-api 和 …
> fix: openai response should contains `model`

- README.md
- common/constants.go
- common/utils.go
- controller/relay-gemini.go
[//]: # (请在提交 PR 前确认所提交的功能可用，附上截图即可，这将有助于项目维护者 review & merge 该 PR，谢谢)
close #831
close #866 
> feat: able to change gemini safety setting

- i18n/en.json
- model/token.go
问题：当DB连接数量达到数据库上限的时候，会报错 “无效的令牌”
排查发现没直接关联的错误的日志
> fix: fix token validation exception handling

- web/berry/src/views/Token/component/TableRow.js
[//]: # (请在提交 PR 前确认所提交的功能可用，附上截图即可，这将有助于项目维护者 review & merge 该 PR，谢谢)
令牌后面的 聊天 主按钮点击没反应，缺少 onClick 事件。
close #950
自测已经修复。
> fix: fix primary chat button in berry theme

- .gitignore
- common/embed-file-system.go
- common/helper/helper.go
- common/logger/logger.go
- controller/billing.go
- controller/channel-test.go
- controller/group.go
- relay/channel/aiproxy/main.go
- relay/channel/openai/token.go
- relay/channel/tencent/main.go
- relay/controller/image.go
一些 linters 告警的小 fix，没有功能变更，自测 OK。
- Improved error handling in various modules for better stability and responsiveness.
- Optimized code in several files for improved efficiency and readability.
- Enhanced user experience by providing more detailed error responses in the controller.
- Strengthened security by ignoring sensitive files in `.gitignore`.
> chore: update code implementation

- relay/channel/baidu/adaptor.go
百度千帆平台上的第三方大模型调用
模型名称需要与百度千帆平台的调试连接末尾名称一致： 如“https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/yi_34b_chat” 中的 yi_34b_chat
通过langchain-openai 调用
> 百度千帆平台上的第三方大模型调用

- relay/channel/baidu/adaptor.go
- relay/channel/baidu/constants.go
close #1144
修复百度模型中URL的字符串判断bug；
添加百度的另外3个向量模型【"bge-large-zh",
"bge-large-en",
"tao-8k",
】
[//]: # (请在提交 PR 前确认所提交的功能可用，附上截图即可，这将有助于项目维护者 review & merge 该 PR，谢谢)
> 修复百度模型中URL的字符串判断bug；

- docker-compose.yml
> feat: add support for private registry in docker-compose.yml

- web/berry/src/views/Setting/component/OtherSetting.js
- web/berry/src/views/Token/component/EditModal.js
在`berry`主题中，存在一个问题，当用户在修改一个令牌后点击新建令牌时，新建令牌弹窗会错误地展示上一次编辑的值。
1. 导航至`令牌`管理页面。
2. 选择任意令牌进行`编辑`。
3. 在编辑界面，点击`取消`返回。
4. 点击`+新建令牌`按钮打开新建令牌弹窗。
新建令牌弹窗应显示空白表单，等待用户输入新的令牌信息。
新建令牌弹窗错误地展示了之前编辑的令牌信息。
> fix: 修复`berry`主题下`令牌`在`编辑`后点击`新建`弹窗值的初始化问题

- relay/channel/zhipu/adaptor.go
Zhi Pu AI Channel's safer compatibility with the temperature topP parameter (0.0, 1)
**Before**
**After**
> ZhiPuAI compatibility with the temperature topP parameter (0.0, 1)

- common/model-ratio.go
上面是官方的文档，以第一个模型为例  2.5/7/1000/0.002=0.178571  代码中计算的时候不应该除以1000000而是1000
> 零一万物的模型价格错误了

- web/berry/src/views/Dashboard/component/StatisticalLineChartCard.js
> fix: fix panel cards style(修复penal卡片高度不一致)

- relay/controller/image.go
- web/air/src/pages/Channel/EditChannel.js
- web/berry/README.md
- web/berry/src/views/Channel/type/Config.js
- web/default/src/pages/Channel/EditChannel.js
Current default API version `2023-06-01-preview` will be retired on 2 April 2024, replace it with the latest `2024-03-01-preview`.
> feat: update default API version for Azure OpenAI

- common/model-ratio.go
> fix: update model-ratio.go 修正文心计费模型名称

- web/default/src/components/LoginForm.js
Optimize Style: Lark Icon Button
> fix:  fix Lark icon button style

- common/image/image.go
- common/logger/logger.go
logger 存在 data race。
用 `sync.Once` 确保 `SetupLogger` 只运行一次
用 `go run -race` 启动后，随便触发点错误日志，就会报大量 race。
```
[SYS] 2024/04/20 - 06:18:10 | One API v0.0.0 started 
[SYS] 2024/04/20 - 06:18:10 | SQL_DSN not set, using SQLite as database 
[SYS] 2024/04/20 - 06:18:10 | database migration started 
[SYS] 2024/04/20 - 06:18:10 | database migrated 
[SYS] 2024/04/20 - 06:18:10 | REDIS_CONN_STRING not set, Redis is not enabled 
[SYS] 2024/04/20 - 06:18:10 | using theme default 
[SYS] 2024/04/20 - 06:18:10 | initializing token encoders 
[SYS] 2024/04/20 - 06:18:10 | token encoders initialized 
2024/04/20 06:18:11 /home/laisky/repo/laisky/one-api/model/ability.go:37 record not found
[0.475ms] [rows:0] SELECT * FROM `abilities` WHERE `group` = "default" and model = "claude-3-haiku2" and enabled = 1 and …
```
> fix: logger race

- relay/adaptor/gemini/main.go
- relay/adaptor/gemini/model.go
close #1348
```
[SYS] 2024/04/23 - 15:36:34 | One API f0.6.5-f09 started 
[SYS] 2024/04/23 - 15:36:34 | running in debug mode 
[SYS] 2024/04/23 - 15:36:34 | using MySQL as database 
[SYS] 2024/04/23 - 15:36:34 | database migration started 
[SYS] 2024/04/23 - 15:36:34 | database migrated 
[SYS] 2024/04/23 - 15:36:34 | REDIS_CONN_STRING not set, Redis is not enabled 
[SYS] 2024/04/23 - 15:36:34 | using theme berry 
[SYS] 2024/04/23 - 15:36:34 | initializing token encoders 
[SYS] 2024/04/23 - 15:36:34 | token encoders initialized 
[DEBUG] 2024/04/23 - 15:36:51 | …
```
> feat: add function and tools support for Gemini

- web/default/src/pages/Channel/EditChannel.js
问题描述：在编辑渠道时，提交编辑内容后，再次编辑会触发 JS 异常导致页面白屏，异常内容：
原因是在 submit 时，误将 `.join(,)`后的结果保存到 state 中，修改了数据类型导致。
异常：
https://github.com/songquanpeng/one-api/assets/1974874/387159d9-da11-4fdd-b288-82f046817249
修复后：
https://github.com/songquanpeng/one-api/assets/1974874/f5ea85b3-1258-4d02-a500-c1ba301c52e0
> fix: fix default theme blank screen when edit channel again

- relay/adaptor/gemini/adaptor.go
- relay/adaptor/gemini/main.go
close #1345
close #1328
```
[SYS] 2024/04/27 - 12:13:57 | One API v0.0.0 started 
[SYS] 2024/04/27 - 12:13:57 | running in debug mode 
[SYS] 2024/04/27 - 12:13:57 | using MySQL as database 
[SYS] 2024/04/27 - 12:13:57 | database migration started 
[SYS] 2024/04/27 - 12:13:57 | database migrated 
[SYS] 2024/04/27 - 12:13:57 | REDIS_CONN_STRING not set, Redis is not enabled 
[SYS] 2024/04/27 - 12:13:57 | using theme berry 
[SYS] 2024/04/27 - 12:13:57 | initializing token encoders 
[SYS] 2024/04/27 - 12:13:57 | token encoders initialized 
[DEBUG] 2024/04/27 - 12:14:18 | 202404271214186411478132525273 | request body: {
"model": "gemini-pro",
"temperature": 0.12,
"max_tokens": 2000,
"stream": true,
"messages": [
{
"role": …
```
> fix: refactor Gemini adaptor to support streaming content generation

- controller/channel-test.go
描述：渠道测试会使用第一个模型名来发起请求，如果使用模型重定向来保证各个渠道对外提供的模型名称一致，而第一个模型的名称又不是该渠道真正可用的模型名时可能会报错。
如下图，使用模型重定向将 Nvidia API 的 `meta/llama3-70b-instruct` 映射为 `llama-3-70b-instruct`，测试时会使用  `llama-3-70b-instruct` 作为模型名称，期望是使用`meta/llama3-70b-instruct`。
```
[SYS] 2024/04/25 - 13:29:16 | {"messages":[{"role":"user","content":"hi"}],"model":"meta/llama3-70b-instruct","max_tokens":2} 
[SYS] 2024/04/25 - 13:29:17 | testing channel #2, response: 
{"id":"chatcmpl-2175002b-36fa-43bc-aafc-809e3f84c498","object":"chat.completion","created":1714022957,"model":"meta/llama3-70b-instruct","choices":[{"index":0,"message":{"role":"assistant","content":"Hi!"},"logprobs":{"content":[{"logprob":0.0},{"logprob":0.0}]}}],"usage":{"prompt_tokens":11,"total_tokens":13,"completion_tokens":2}} 
```
> feat: use mapped model name to test

- relay/adaptor/anthropic/main.go
某代理提供的 claude 接口返回的 stream 中，`event:` 与 `data:` 之后没有空格，会导致解析不出数据，只返回一行 `data: [DONE]`。
该PR放宽了 stream 的格式限制，`event:` 与 `data:` 之后有无空格均支持。
> fix: claude stream response parse

- relay/adaptor/zhipu/adaptor.go
> fix: fix zhipu embedding error when input is array but not string

- relay/controller/helper.go
目前如果 API 没有传递 max_tokens 参数，getPreConsumedQuota 就不会计算 prompt tokens，可能会造成超额使用的情况。比如我截图的这个例子，虽然我设置了请求预扣费额度，但是用户的这个请求产生的额度，远远超出了他账户剩余的额度，因为他用的客户端没有传递 max_tokens，getPreConsumedQuota 方法没有计算到 prompt tokens， 他的 prompt tokens 还非常长。
像 Claude 3 Opus 这种支持超长上下文，价格还不便宜的模型，如果用户传递超长的 prompt，不计算 prompt tokens 很容易被用户超额使用几美元。
我把 getPreConsumedQuota 改成了默认会计算 prompt tokens。
> fix: fix getPreConsumedQuota

- relay/adaptor/openai/constants.go
- relay/billing/ratio/model.go
> feat: support gpt-4o

- web/berry/package.json
close #1456 
修复新版本 react-apexcharts 和 apexcharts 的版本冲突的问题，该冲突会导致在Zeabur等平台上部署失败，详情见issue
> fixed the bug of react-apexcharts version

- controller/user.go
> feat: generate default token after register

- relay/adaptor/gemini/adaptor.go
- relay/adaptor/gemini/constants.go
- relay/adaptor/gemini/main.go
- relay/adaptor/gemini/model.go
close #1313
close #868
```
[SYS] 2024/05/28 - 14:34:52 | One API v0.0.0 started 
[SYS] 2024/05/28 - 14:34:52 | using MySQL as database 
[SYS] 2024/05/28 - 14:34:52 | database migration started 
[SYS] 2024/05/28 - 14:34:52 | database migrated 
[SYS] 2024/05/28 - 14:34:52 | REDIS_CONN_STRING not set, Redis is not enabled 
[SYS] 2024/05/28 - 14:34:52 | using theme berry 
[SYS] 2024/05/28 - 14:34:52 | initializing token encoders 
[SYS] 2024/05/28 - 14:34:57 | token encoders initialized 
[SYS] 2024/05/28 - 14:35:50 | model ratio not found: text-embedding-004 
[INFO] 2024/05/28 - 14:35:50 | 202405281435508260323702375031 | user 1 has enough quota 499999972164332, trusted and no need to pre-consume 
[GIN] 2024/05/28 - 14:35:50 …
```
> feat: Support gemini embeddings (text-embedding-004,embedding-001)

- relay/adaptor/gemini/main.go
close #1408
close #1386
___
理论上早期的版本应该没有返回FinishReason？所以流不会被截断。
但是在v0.6.7左右的版本修复stream流问题时这部分被修正了#1382，引入了FinishReason字段。涉及问题#1345、
#1328。
但是有个比较尴尬的地方在于，实际上Gemini的API本身就在每个流message中返回STOP（看起来跟早期的Gemini的表现不太一致，不知道为什么会出现这个问题）。
**因为是流式返回，没法准确预知哪个是最后一条message，只能暂时去掉FinishReason字段了。**
___
启动：
```
[SYS] 2024/05/28 - 15:26:32 | One API v0.0.0 started 
[SYS] 2024/05/28 - 15:26:32 | running in debug mode 
[SYS] 2024/05/28 - 15:26:32 | SQL_DSN not set, using SQLite as database 
[SYS] 2024/05/28 - 15:26:32 | database migration started 
[SYS] 2024/05/28 - 15:26:32 | database migrated 
[SYS] 2024/05/28 - 15:26:32 | REDIS_CONN_STRING not set, Redis is not enabled 
[SYS] 2024/05/28 - 15:26:32 | using theme default 
[SYS] 2024/05/28 - …
```
> fix: Gemini streaming return being truncated by FinishReason.

- relay/adaptor/xunfei/main.go
- relay/adaptor/xunfei/model.go
修复了讯飞星火的函数调用功能。
调用Spark Pro/Max 的 Function call ，只会返回普通对话形式的回答，而不是 function call格式的的回答。
原因是在请求体中多包了一层json，导致星火不能正确解析请求体中的 function call 的相关参数。
现在修正了请求体的格式，能够按预期回答。
close #1543 #1524 #1493 #1457
我已确认该 PR 已自测通过，以 openai 标准格式的同一个 req 调用星火，智谱和openai 的 function call 类型对话，均能正常返回function call格式的相同的 resp。相关截图如下：
> fix: fix sparkdesk function call

- relay/adaptor/openai/main.go
测试结果如上。minimax的返回只有totaltoken没有响应提示和补全，经由new-api作者提示后发现了问题。处理了非流返回的判断
close #1550
> fix minimax empty log

- relay/adaptor/anthropic/constants.go
- relay/adaptor/aws/main.go
- relay/billing/ratio/model.go
- web/air/src/pages/Channel/EditChannel.js
> chore: Add support for Claude Sonnet 3.5

- common/message/email.go
某些 smtp 服务器不需认证(如内部的 postfix ), 在传递了 auth 信息后, 会报错显示 `smtp: server doesn't support AUTH`
本 pr 会解决这个问题
> feat: support smtp without auth

- relay/adaptor/cloudflare/adaptor.go
- relay/adaptor/cloudflare/main.go
- relay/adaptor/cloudflare/model.go
https://developers.cloudflare.com/ai-gateway/providers/workersai/#openai-compatible-endpoints
> feat: cloudflare support native openai api

- relay/adaptor/openai/token.go
close #1633
现在不会引发nil了，会最后直接把错错误抛出
> fix: 修复4v请求下text参数缺少引发的nil

- relay/model/general.go
问题描述：使用【模型重定向】功能后，one-api 转发对话时丢失 stop 参数。
翻查代码，定位到：
当 `isModelMapped` 为真，`shouldResetRequestBody` 也为真，调用
`jsonStr, err := json.Marshal(textRequest)` 将 `textRequest` 序列化成字符串。
由于 `textRequest` 的类型 `GeneralOpenAIRequest` 并不包含 `stop` 字段，导致模型重定向后字段丢失。
close #1558 
在 issue 搜索了一下，这个 issue 可能遇到类似的情况：
https://github.com/songquanpeng/one-api/issues/1558
> feat: add field stop in GeneralOpenAIRequest

- common/config/config.go
- relay/adaptor/anthropic/adaptor.go
- relay/adaptor/vertexai/claude/model.go
- relay/adaptor/vertexai/registry.go
- relay/adaptor/vertexai/token.go
- relay/channeltype/url.go
- relay/meta/relay_meta.go
claude-3-5-sonnet 支持 8k 输出，实际上就是加了一行 header
> feat: extend anthropic header to support 8k context windows

- relay/adaptor/doubao/main.go
- relay/controller/text.go
> fix: support embedding models for doubao

- relay/adaptor/openai/constants.go
- relay/adaptor/openai/token.go
- relay/billing/ratio/model.go
resolve issue: https://github.com/songquanpeng/one-api/issues/1664
ps: 有一个小坑， 4o mini 识图模型的tile价格对标 4o，为mini的token价格的33倍。因此我修改了图片token计算方式
ref: [additionalCost](https://openai.com/api/pricing/)
> feat: support gpt-4o mini

- relay/adaptor/ollama/adaptor.go
- relay/adaptor/ollama/main.go
- relay/adaptor/ollama/model.go
修改Ollama嵌入API为最新版本, 支持多文本嵌入, 添加Options参数到嵌入请求中。
close #1305 #1407
> feat: update Ollama embedding API to latest version with multi-text embedding support

- relay/adaptor/ollama/main.go
- relay/adaptor/ollama/model.go
- relay/model/general.go
**已实现：**
1. 支持通过`max_tokens`（对应ollama的num_predict）参数限制输出token数
2. 支持通过`num_ctx`（ollama原生参数）参数设定更改ollama默认context window大小（默认仅1k/2k上下文）
**有个问题：**
下图中改动的部分是因为原本的代码会导致报错，console打印后发现原本的data就是正确的json格式不需要对花括号进行增减处理。但奇怪的是目前我通过docker compose部署的正式版本也是能正常使用的，正式版本并没有我对这两行的修改（也可能部署的版本本来没有这两行？没有去查看，总之修改之后添加了条件判断，对两种不同状况都能有效应对）。
目前已确认并非个案， #1702 也是同样的问题，但我觉得条件判断会比直接改掉健壮性更强
close #1691
> feat: add Max Tokens and Context Window Setting Options for Ollama Channel

- relay/adaptor/cloudflare/constant.go
新增Cloudflare支持的免费Beta模型 Llama 3.1 8b
> chore: Add Cloudflare New Free Model Llama 3.1 8b

- monitor/manage.go
[]: # (请按照以下格式关联 issue)
[]: # (请在提交 PR 前确认所提交的功能可用，需要附上截图，谢谢)
[]: # (项目维护者一般仅在周末处理 PR，因此如若未能及时回复希望能理解)
[]: # (开发者交流群：910657413)
[]: # (请在提交 PR 之前删除上面的注释)
close #1764  
> fix: Groq organization not auto-disabled when blocked

- controller/billing.go
- model/token.go
when id=0, getTokenById return token nil, make panic
> fix: getTokenById return token nil, make panic

- relay/adaptor/openai/constants.go
- relay/billing/ratio/model.go
ref: https://openai.com/index/introducing-structured-outputs-in-the-api/
> 通过切换到新的gpt-4o-2024-08-06, developers save 50% on inputs ($2.50/1M input tokens) and 33% on outputs ($10.00/1M output tokens) compared to gpt-4o-2024-05-13.
> 与 gpt-4o-2024-05-13 相比，开发者可节省 50%的输入成本（每百万输入令牌$2.50）和 33%的输出成本（每百万输出令牌$10.00）
卷起来！
> feat: support new openai models (4o 0806, chatgpt-4o-latest)

- relay/adaptor/openai/main.go
The usage is missing.
close #no_issue
The change  is verified in the self-hosted service.
> fix: return the usage info if usage not null

- model/token.go
If MySQL is used as the database, the default data type for "token models" is "varchar(191)". When we create a token object with many models, the model data string will be truncated in the database.
在使用 MySQL 作为数据库时， tokens 表中的 models 字段的类型是 varchar， 当创建 token 时配置的模型数量过多时，会导致数据不能完全保存。
有另外一个有点关系的 issue：  #1483
> fix: modify the type of token models to be text

- common/gin.go
- middleware/distributor.go
> feat: support multipart/form-data format request

- relay/adaptor/xunfei/constants.go
- relay/adaptor/xunfei/main.go
- relay/billing/ratio/model.go
- web/air/src/pages/Channel/EditChannel.js
- web/berry/src/views/Channel/type/Config.js
> feat: support SparkDesk-v3.5-32K

- relay/adaptor/anthropic/constants.go
- relay/adaptor/aws/claude/main.go
- relay/billing/ratio/model.go
- web/air/src/pages/Channel/EditChannel.js
增加 anthropic.claude-3-5-sonnet-20241022-v2:0
> feat: add support for Claude Sonnet 3.5 v2

- relay/adaptor/xunfei/main.go
> fix: update Spark Lite's domain to lite

- relay/adaptor/gemini/constants.go
- relay/adaptor/gemini/main.go
- relay/adaptor/vertexai/gemini/adapter.go
- relay/billing/ratio/model.go
close #1993 
close #1979
支持返回多parts时文本合并，支持gemini-2.0-flash-thinking-exp模型（steam模式/非stream模式）。
> feat: enhance response handling to support gemini-2.0-thinking

- relay/adaptor/anthropic/constants.go
Remove the duplicate `claude-3-5-haiku-20241022` causing issue 1928
close #1928 
过于浅显的错误，我就不 build 了……
> fix: remove the duplicate `claude-3-5-haiku-20241022` in Anthropic's base model list

- README.md
- common/redis.go
> feat: support Redis Sentinel and Redis Cluster

- controller/channel-billing.go
- web/berry/src/views/Channel/component/TableRow.js
- web/default/src/components/ChannelsTable.js
> feat: add balance query support for DeepSeek

- relay/adaptor/openai/constants.go
- relay/billing/ratio/model.go
> feat: support gpt-4o-2024-11-20

- relay/adaptor/tencent/model.go
- relay/billing/ratio/model.go
> fix: fix hunyuan paramete & update price

- relay/adaptor/groq/constants.go
groq 的 model 重复了，这个 pr 移除了最新添加的 model
我已确认该 PR 已自测通过
> fix: remove duplicated model

- relay/billing/ratio/group.go
- relay/billing/ratio/model.go
This pull request fixes a critical concurrency issue where multiple goroutines were concurrently reading from and writing to our global maps, causing a runtime panic with the error "concurrent map read and map write." 
The issue was observed in functions like `GetModelRatio` and others that access global maps such as `ModelRatio`, `GroupRatio`. In Go, built-in maps are not safe for concurrent use, which led to data races and eventual panics under high load.
- **Added synchronization:**
- Introduced `sync.RWMutex` locks to protect access to `ModelRatio` and `GroupRatio`.
- Similarly, added read/write locks for `GroupRatio` to ensure thread-safe operations.
- **Updated functions:**
- Modified functions like `GetModelRatio` and `UpdateModelRatioByJSONString` to use the appropriate read and …
> fix: add read/write locks for ModelRatio and GroupRatio to prevent concurrency
