docker-compose.yml
one-api.service

1.健康检查改为curl查看返回值。
2.修改回dockerhub获取镜像

feat: add Docker Compose support

---

controller/relay-utils.go
controller/relay.go

参照官方的token计算cookbook
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb 
https://github.com/pkoukk/tiktoken-go/issues/6
根据以下测试
```bash
curl -w %{http_code} https://api.openai.com/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer sk-xxxxxxx" \
-d '{
"model": "gpt-3.5-turbo",
"messages": [{"role": "user", "content": "Say this is a test!"}],
"temperature": 0.7,
"stream": false
}'
```
可以得到官方token计算结果
```text
"usage":{"prompt_tokens":14,"completion_tokens":5,"total_tokens":19},
"choices":[{"message":{"role":"assistant","content":"This is a test!"}
```
根据以下测试
```go
package main
import (
"fmt"
"github.com/pkoukk/tiktoken-go"
"github.com/sashabaranov/go-openai"
)
// NumTokensFromMessages
func …
```

Make token calculation more accurate.

---

controller/relay.go

https://github.com/songquanpeng/one-api/issues/166

 fix: the prompt field can be array type now (close #166)

---

controller/channel-billing.go
web/src/components/ChannelsTable.js

支持 AIProxy 更新余额。
参考文档：https://docs.aiproxy.io/dev/quick-start

Add: support update AIProxy balance

---

README.md
common/constants.go
controller/channel-billing.go
web/src/components/ChannelsTable.js
web/src/constants/channel.constants.js

添加支持 api2gpt.com 平台
添加支持 api2gpt.com 余额查询

support API2GPT platform

---

common/constants.go
controller/channel-billing.go
web/src/components/ChannelsTable.js
web/src/constants/channel.constants.js

feat: add AIGC2D Channel

---

bin/time_test.sh

default value is gpt-3.5-turbo

chore: add model parameter to the time_test script

---

router/relay-router.go

via: https://platform.openai.com/docs/api-reference/models/list
close #318

fix: relay router typo for List models (#318)

---

controller/relay-openai.go
controller/relay-text.go
controller/relay.go

试着改进了下在自定义渠道没返回 usage 的时候依据数据量计费，避免不计费的问题。

改进某些没返回 usage 的自定义渠道计费的问题

---

controller/relay-ali.go
controller/relay-baidu.go
controller/relay-claude.go
controller/relay-palm.go
controller/relay-utils.go
controller/relay-xunfei.go
controller/relay-zhipu.go
controller/relay.go

流式传输统一finish_reason字段，未完成返回null，完成返回“stop” #372

统一接口的finish_reason字段

---

controller/relay-ali.go
controller/relay-baidu.go
controller/relay-claude.go
controller/relay-openai.go
controller/relay-palm.go
controller/relay-utils.go
controller/relay-xunfei.go
controller/relay-zhipu.go

封装流式传输响应头的设置

---

README.md
controller/relay-baidu.go
model/main.go
web/src/components/ChannelsTable.js

文心千帆的向量模型接口问题（请求input是数组报错） #397

【百度文心千帆】文心千帆的向量模型接口问题（请求input是数组报错）

---

README.en.md
README.ja.md
README.md

I created Japanese translated README.

Add Japanese README

---

common/model-ratio.go
controller/relay-text.go

fix: Claude model ratio

---

common/model-ratio.go
controller/model.go
controller/relay-ali.go
controller/relay-baidu.go
controller/relay-text.go
controller/relay.go
web/src/pages/Channel/EditChannel.js

支持阿里的 embedding 模型

---

controller/relay-text.go
controller/relay-xunfei.go

讯飞支持非stream模式

---

model/log.go

NULL转换int时出现不支持的错误

---

common/constants.go
common/database.go
common/utils.go
model/ability.go
model/cache.go
model/channel.go
model/main.go
model/redemption.go
model/user.go

fix postgresql support

---

model/log.go

fix: Incorrect column name on log search

---

controller/relay-image.go
controller/relay-openai.go
controller/relay-text.go
middleware/auth.go

feat: 删除relay-text中的consumeQuota变量

---

model/user.go

fix: fix SearchUsers not working if using PostgreSQL

---

i18n/en.json
web/src/components/ChannelsTable.js

fix: fix button copywriting

---

web/berry/src/menu-items/panel.js
web/berry/src/utils/api.js
web/berry/src/views/Channel/component/EditModal.js

- 跳转登录地址错误
- 普通用户菜单显示个人设置页面
- 删除了多余的输入框。

fix: fix some issues with berry

---

web/berry/src/layout/MinimalLayout/index.js
web/berry/src/ui-component/Logo.js
web/berry/src/views/Channel/component/EditModal.js
web/berry/src/views/Token/component/TableRow.js

- 修复自定义logo会导致导航栏拉高遮挡内容
- 优化渠道模型下拉框用户体验
- 修复过期key无法重新启用的问题
- 修复 gemini base_url必填的问题

fix: fix bugs with theme berry

---

relay/channel/anthropic/adaptor.go

[//]: # (请在提交 PR 前确认所提交的功能可用，附上截图即可，这将有助于项目维护者 review & merge 该 PR，谢谢)
This fixes wrong provider field `owned_by` output in list models API

fix: model name typo

---

common/model-ratio.go

fix: fix ratio of gpt-3.5-turbo (close #1011)

---

web/berry/src/constants/ChannelConstants.js

Fix the minor error in the value of Moonshot in the berry theme

fix: change Moonshot value to 25

---

controller/token.go
controller/user.go
model/token.go
model/user.go
web/air/src/components/TokensTable.js
web/air/src/components/UsersTable.js
web/default/src/components/TokensTable.js
web/default/src/components/UsersTable.js

feat: add user list sorting and pagination enhancements (#77, #602)

---

relay/controller/audio.go

支持 [Azure OpenAI 的 TTS 模型](https://learn.microsoft.com/en-us/azure/ai-services/openai/text-to-speech-quickstart?tabs=command-line#rest-api)。
渠道信息：

feat: support Azure OpenAI TTS.

---

README.en.md
README.ja.md
README.md

docs: update README

---

relay/channel/openai/adaptor.go

feat: 移除 azure model 的 TrimSuffix

---

relay/channel/ollama/adaptor.go
relay/channel/ollama/main.go
relay/channel/ollama/model.go

close #1216
增加对ollama的embedding接口调用支持

feat: 支持 ollama 的 embedding 接口

---

common/model-ratio.go
relay/channel/zhipu/adaptor.go
relay/channel/zhipu/constants.go
relay/channel/zhipu/main.go
relay/channel/zhipu/model.go

feat: add embedding-2 support for zhipu

---

common/model-ratio.go
relay/channel/baidu/adaptor.go
relay/channel/baidu/constants.go

feat: update baidu model name & ratio

---

web/default/src/components/LoginForm.js

chore: Resolve the issue of onclick event scope for custom Lark button

chore: resolve the issue of onclick event scope for custom Lark button

---

relay/adaptor/groq/constants.go
relay/billing/ratio/model.go

feat: groq support Llama3 now

---

relay/adaptor/ollama/main.go

ollama `llava:34b-v1.6` model, pass test
close #1375

feat: support for the ollama vision model

---

web/berry/src/constants/ChannelConstants.js
web/berry/src/constants/SnackbarConstants.js
web/berry/src/utils/common.js
web/berry/src/views/Authentication/AuthForms/ResetPasswordForm.js
web/berry/src/views/Channel/component/EditModal.js
web/berry/src/views/Channel/component/NameLabel.js
web/berry/src/views/Channel/index.js
web/berry/src/views/Channel/type/Config.js
web/berry/src/views/Profile/index.js
web/berry/src/views/Redemption/component/TableRow.js
web/berry/src/views/Token/component/TableRow.js
web/berry/src/views/Topup/component/InviteCard.js

- 适配了`AWS Claude`/`Cloudflare`/`Coze` 渠道
- 支持从服务器填入对应渠道模型
- 修复在复制失败时为弹出提示
- 优化提示，增加关闭按钮，防止提示遮挡按钮

feat: berry theme update & bug fix

---

relay/adaptor/openai/token.go

fix: fix gpt-4o token encoding

---

controller/relay.go

chore: print user id when relay error happened

---

relay/billing/ratio/image.go
relay/controller/image.go

fix: add prefixes to image models to solve the problem of duplicate models

---

relay/adaptor/cloudflare/main.go

feat: post all messages for cloudflare

---

relay/adaptor/xunfei/model.go

fix: xunfei interface call 4001 error

---

middleware/distributor.go
model/channel.go
relay/adaptor/xunfei/adaptor.go
relay/adaptor/xunfei/main.go
relay/adaptor/xunfei/model.go
web/default/src/pages/Channel/EditChannel.js

修复了讯飞星火的函数调用功能，以及Spark Lite 接口不支持函数调用导致的报错
close #1524 #1493 #1457 

fix: support for Spark Lite model

---

web/berry/src/views/Channel/component/EditModal.js

修复组装key时，判断错误
https://github.com/songquanpeng/one-api/issues/912#issuecomment-2138663838
https://github.com/songquanpeng/one-api/issues/912#issuecomment-2138895000

fix: berry theme channel edit settings key error

---

controller/user.go
model/user.go

fix: fix default token not created in some cases

---

relay/adaptor/tencent/adaptor.go
relay/adaptor/tencent/constants.go
relay/adaptor/tencent/main.go
relay/adaptor/tencent/model.go
relay/channeltype/url.go

close #1452, close #739
调用最新版本腾讯混元截图
项目启动成功截图

feat: support tencent v3 api

---

.github/workflows/ci.yml

使用 codecov 上传覆盖率, 获得更好的体验
需要owner 提前授权一下, 参考: https://docs.codecov.com/docs/quick-start#prerequisites

ci: use codecov to upload coverage report

---

README.en.md
README.md

docs: add related projects

---

web/air/src/components/PersonalSetting.js

feat(ui): show available models for air theme

---

controller/channel-test.go
web/default/src/components/ChannelsTable.js

feat: support test specific model

---

common/config/config.go
model/main.go

issues https://github.com/songquanpeng/one-api/issues/1589

feat: add initial root access token

---

README.md
relay/adaptor/novita/constants.go
relay/adaptor/novita/main.go
relay/adaptor/openai/adaptor.go
relay/adaptor/openai/compatible.go
relay/channeltype/define.go
relay/channeltype/url.go
web/berry/src/constants/ChannelConstants.js
web/default/src/constants/channel.constants.js

新增渠道：[Novita AI](https://novita.ai)

feat: add Novita AI as model provider

---

relay/adaptor/cloudflare/adaptor.go

fix: impl cloudflare worker ai gateway

---

relay/adaptor/vertexai/adaptor.go
relay/adaptor/vertexai/claude/adapter.go

feat: vertexai support proxy url(example: cloudflare ai gateway) and fix some vertexai bug

---

README.md

QChatGPT 3.x 修改了配置方式，辛苦合并。
\ （仅文档修改）

docs: update introduction for QChatGPT

---

relay/adaptor/gemini/constants.go
relay/adaptor/groq/constants.go
relay/billing/ratio/model.go

feat: update gemini model

---

model/log.go

fix: postgres use COALESCE replace null

---

monitor/manage.go

feat: update disabled channel

---

relay/model/general.go

（此处放上测试通过
的截图，如果不涉及前端改动或从 UI 上无法看出，请放终端启动成功的截图）

feat: ResponseFormat support json_schema

---

relay/adaptor/stepfun/constants.go
relay/billing/ratio/image.go
relay/billing/ratio/model.go

feat: update stepfun's models

---

web/air/src/components/TokensTable.js
web/berry/src/views/Token/component/TableRow.js
web/default/src/components/TokensTable.js

feat: add lobechat open link options

---

relay/adaptor/tencent/constants.go
relay/adaptor/xunfei/constants.go
relay/adaptor/xunfei/main.go
relay/billing/ratio/model.go
web/air/src/pages/Channel/EditChannel.js
web/berry/src/views/Channel/type/Config.js

 feat: support SparkDesk-v3.1-128K

---

controller/channel-billing.go
web/berry/src/views/Channel/component/TableRow.js
web/default/src/components/ChannelsTable.js

feat: support siliconflow usage

---

web/air/src/components/TokensTable.js
web/berry/src/views/Token/component/TableRow.js
web/default/src/components/TokensTable.js

fix：unsuccessful lobechat redirection link

---

relay/adaptor/vertexai/gemini/adapter.go

feat: add Vertex AI gemini-1.5-pro-002 and gemini-1.5-flash-002

---

controller/channel-test.go

fix: use modelMap when testing a channel

---

relay/adaptor/gemini/main.go
relay/adaptor/gemini/model.go

feat: update Gemini adaptor to support custom response format

---

relay/adaptor/anthropic/constants.go
relay/adaptor/aws/claude/main.go
relay/billing/ratio/model.go
web/air/src/pages/Channel/EditChannel.js

feat: added support for Claude 3.5 Haiku

---

README.md
relay/adaptor/openai/compatible.go
relay/adaptor/xai/constants.go
relay/billing/ratio/model.go
relay/channeltype/define.go
relay/channeltype/url.go
web/air/src/constants/channel.constants.js
web/berry/src/constants/ChannelConstants.js
web/berry/src/views/Channel/type/Config.js
web/default/src/constants/channel.constants.js

feat: add support for xAI

---

middleware/gzip.go
router/relay.go

feat: support gzip decode

---

relay/adaptor/ali/constants.go
relay/billing/ratio/model.go

feat: update qwen model and price

---

relay/controller/audio.go

chore: update model mapping implementation for audio

---

web/berry/src/utils/common.js

issue: https://github.com/songquanpeng/one-api/issues/2040
close #2040

fix: fix berry copy token

---

relay/adaptor/tencent/adaptor.go
relay/adaptor/tencent/constants.go
relay/adaptor/tencent/main.go
relay/adaptor/tencent/model.go

- 本提交适配了腾讯混元的词嵌入模型 hunyuan-embedding，模型文档地址：https://cloud.tencent.com/document/product/1729/102832
- 适配了腾讯ChatCompletions模型接口的json key值变化。
close #1799

feat: support hunyuan-embedding

---

relay/billing/ratio/model.go

feat: update Zhipu model prices

---

common/gin.go

fix: audio transcription 400 error (#1882)

---

relay/billing/ratio/model.go

https://docs.anthropic.com/en/docs/about-claude/models

feat: update anthropic model prices
